import "dart:io";

/// Translates `.env` into iOS build settings, by writing the git-ignored
/// `ios/Flutter/Local.xcconfig`.
///
/// Two settings live here for the same reason: Xcode resolves them at build
/// time and can't read a Dart-side value, and neither belongs in a tracked file.
///
/// 1. **`STERA_CODE_SIGN_ENTITLEMENTS`** — `Runner.entitlements` declares the
///    Sign in with Apple capability, which free/personal Apple developer teams
///    cannot provision, so an unmodified checkout won't sign onto a device
///    without a paid account. A `NO_AUTH_MODE` build never calls Sign in with
///    Apple, so it points at the empty `RunnerNoAuth.entitlements` instead.
/// 2. **`GOOGLE_REVERSED_CLIENT_ID`** — the URL scheme Google Sign-In requires.
///    `Info.plist` references it as `$(GOOGLE_REVERSED_CLIENT_ID)` so a real
///    client id never lands in a tracked file: this repo ships a placeholder on
///    purpose and a fork shouldn't inherit somebody else's id.
///
/// Run via `dart run tool/sync_ios_config.dart` (also invoked by
/// `bun run pub-get:mobile`). Safe and idempotent to re-run.
Future<void> main(List<String> args) async {
  final repoRoot = Directory.current.path;
  final envPath = File("$repoRoot/.env");
  final envExamplePath = File("$repoRoot/.env.example");

  final envFile = envPath.existsSync() ? envPath : envExamplePath;
  final values = envFile.existsSync()
      ? _parseEnv(await envFile.readAsString())
      : <String, String>{};

  final raw = (values["NO_AUTH_MODE"] ?? "").trim().toLowerCase();
  final noAuth = raw == "true" || raw == "1";

  final flutterDir = Directory("$repoRoot/ios/Flutter");
  if (!flutterDir.existsSync()) {
    stderr.writeln(
      "ios/Flutter not found at ${flutterDir.path} — skipping iOS config sync.",
    );
    exit(0);
  }

  // `APPLE_SIGN_IN=false` is the development escape hatch: personal Apple teams
  // can't provision the capability, so keeping it would make the authed build
  // unsignable — and therefore Google sign-in untestable too. Only a literal
  // false/0 disables it; anything else keeps Sign in with Apple, because the App
  // Store requires it from any app offering third-party sign-in.
  final appleRaw = (values["APPLE_SIGN_IN"] ?? "").trim().toLowerCase();
  final appleSignIn = !(appleRaw == "false" || appleRaw == "0");

  final entitlements = (noAuth || !appleSignIn)
      ? "Runner/RunnerNoAuth.entitlements"
      : "Runner/Runner.entitlements";

  final buffer = StringBuffer()
    ..writeln(
      "// GENERATED by tool/sync_ios_config.dart from .env — do not edit.",
    )
    ..writeln("// NO_AUTH_MODE=$noAuth")
    ..writeln("STERA_CODE_SIGN_ENTITLEMENTS = $entitlements");

  // Google Sign-In is dead weight in a no-auth build, and that `.env` may carry
  // no client id at all — leave the placeholder default standing there.
  final iosClientId = (values["GOOGLE_IOS_CLIENT_ID"] ?? "").trim();
  final hasClientId = !noAuth && iosClientId.isNotEmpty;
  if (hasClientId) {
    buffer.writeln(
      "GOOGLE_REVERSED_CLIENT_ID = ${_reversedGoogleClientId(iosClientId)}",
    );
  }

  // Signing identity. Kept out of project.pbxproj because DEVELOPMENT_TEAM is an
  // Apple account identifier and the bundle id must be unique per publisher —
  // committing either leaks it and hijacks every fork's build.
  final team = (values["IOS_DEVELOPMENT_TEAM"] ?? "").trim();
  final bundleId = (values["IOS_BUNDLE_ID"] ?? "").trim();
  if (team.isNotEmpty) {
    buffer
      ..writeln("STERA_DEVELOPMENT_TEAM = $team")
      // A team can only be resolved to a profile automatically; leaving this
      // Manual would fail with "no profile matching" despite a valid team.
      ..writeln("STERA_CODE_SIGN_STYLE = Automatic");
  }
  if (bundleId.isNotEmpty) {
    buffer.writeln("STERA_BUNDLE_ID = $bundleId");
  }

  await File(
    "${flutterDir.path}/Local.xcconfig",
  ).writeAsString(buffer.toString());

  if (noAuth) {
    stdout.writeln(
      "NO_AUTH_MODE — signing with $entitlements (no Sign in with Apple).",
    );
    return;
  }

  stdout.writeln(
    team.isEmpty
        ? "No IOS_DEVELOPMENT_TEAM set — device builds will need signing configured."
        : "Signing as team $team${bundleId.isEmpty ? "" : " ($bundleId)"}.",
  );
  stdout.writeln("Entitlements: $entitlements.");
  if (!appleSignIn) {
    stdout.writeln(
      "⚠️  APPLE_SIGN_IN=false — Sign in with Apple is dropped from this build. "
      "Development only; the App Store requires it alongside Google sign-in.",
    );
  }
  stdout.writeln(
    hasClientId
        ? "Google Sign-In URL scheme set from GOOGLE_IOS_CLIENT_ID."
        : "⚠️  GOOGLE_IOS_CLIENT_ID is unset — Google Sign-In will fail with "
              "\"missing support for the following URL schemes\".",
  );
}

String _reversedGoogleClientId(String iosClientId) {
  if (iosClientId.endsWith(".apps.googleusercontent.com")) {
    final clientPart = iosClientId.split(".apps.googleusercontent.com").first;
    return "com.googleusercontent.apps.$clientPart";
  }

  return iosClientId;
}

Map<String, String> _parseEnv(String contents) {
  final values = <String, String>{};

  for (final rawLine in contents.split("\n")) {
    final line = rawLine.trim();
    if (line.isEmpty || line.startsWith("#")) {
      continue;
    }

    final separator = line.indexOf("=");
    if (separator <= 0) {
      continue;
    }

    final key = line.substring(0, separator).trim();
    var value = line.substring(separator + 1).trim();

    if ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))) {
      value = value.substring(1, value.length - 1);
    }

    values[key] = value;
  }

  return values;
}
