/**
 * `70-assets`.
 *
 * Two decisions worth stating up front, because both are load-bearing:
 *
 * 1. **`flutter_launcher_icons` is added; `flutter_native_splash` is not.**
 *    The launcher-icon tool resizes every iOS and Android density from a single
 *    1024px master, which is exactly the boring work you want automated. The
 *    splash tool, by contrast, regenerates `LaunchScreen.storyboard` from its
 *    own template - which would delete this repo's custom two-label,
 *    full-bleed-texture launch screen. The storyboard is patched surgically in
 *    `60-theme` instead.
 *
 * 2. **The engine rasterises; it does not invent artwork.** If a fork supplies
 *    no icon, `packages/brand/apply.ts` writes a placeholder monogram and says so, rather
 *    than silently shipping upstream's logo under a new name.
 *
 * Everything under `packages/brand/generated/` is committed, so CI and other
 * contributors need neither sharp nor the original art to build.
 */

import { join } from "node:path";

import {
  GENERATED_DIR,
  MIN_ICON_SOURCE,
  monochrome,
  monogramSvg,
  probe,
  resizeTo,
  square,
} from "../lib/raster.ts";
import { hexToCss } from "../lib/derive.ts";
import {
  bundledFontPath,
  orphanedFontFiles,
  renderPubspecFonts,
} from "../lib/fonts.ts";
import { applyTokens } from "../lib/tokens.ts";
import type { Brand, Change, Ctx, Transform } from "../lib/types.ts";

const PUBSPEC = "apps/mobile/pubspec.yaml";
const CONFIG_START = "# brand:launcher-icons:start";
const CONFIG_END = "# brand:launcher-icons:end";

const LAUNCHER_ICONS_VERSION = "^0.14.4";

const ICON_MASTER = `${GENERATED_DIR}/icon_1024.png`;
const ICON_FOREGROUND = `${GENERATED_DIR}/icon_foreground_1024.png`;
const ICON_MONOCHROME = `${GENERATED_DIR}/icon_monochrome_1024.png`;

const PLAY_STORE_ICON = "apps/mobile/android/app/src/main/res/play_store_512.png";
const LOGO_LIGHT = "apps/mobile/assets/icon/logo_light.png";
const LOGO_DARK = "apps/mobile/assets/icon/logo_dark.png";
// The root README's `<h1>` renders these. A fork that skipped them would have
// its own launcher icon and upstream's mark on its own front page.
const README_LOGO_LIGHT = "assets/logo_light.png";
const README_LOGO_DARK = "assets/logo_dark.png";
const LAUNCH_LOGO_DIR = "apps/mobile/ios/Runner/Assets.xcassets/LaunchLogo.imageset";
const SPLASH_TEXTURE_DIR =
  "apps/mobile/ios/Runner/Assets.xcassets/SplashTexture.imageset";

/**
 * The launcher-icons config block, written between markers so it can be
 * replaced wholesale on every run without accumulating duplicates.
 *
 * `remove_alpha_ios` is mandatory: App Store validation rejects an icon with an
 * alpha channel. `adaptive_icon_monochrome` is supplied because this repo
 * already ships a monochrome layer - omit it and Android 13+ themed icons
 * silently regress to a generic badge.
 */
const configBlock = (brand: Brand): string =>
  [
    CONFIG_START,
    "# Generated by packages/brand/apply.ts from packages/brand/brand.json - edit that, not this.",
    "flutter_launcher_icons:",
    `  image_path: "../../${ICON_MASTER}"`,
    '  android: "ic_launcher"',
    "  ios: true",
    "  remove_alpha_ios: true",
    "  min_sdk_android: 24",
    `  adaptive_icon_background: "${hexToCss(brand.assets.iconBackgroundColor)}"`,
    `  adaptive_icon_foreground: "../../${ICON_FOREGROUND}"`,
    `  adaptive_icon_monochrome: "../../${ICON_MONOCHROME}"`,
    CONFIG_END,
  ].join("\n");

const withLauncherIconsDep = (pubspec: string): string => {
  if (pubspec.includes("flutter_launcher_icons:")) {
    return pubspec;
  }
  return pubspec.replace(
    /^dev_dependencies:\n/m,
    `dev_dependencies:\n  flutter_launcher_icons: ${LAUNCHER_ICONS_VERSION}\n`
  );
};

const FONTS_START = "  # brand:fonts:start";
const FONTS_END = "  # brand:fonts:end";

/**
 * Replaces the `fonts:` list under `flutter:`.
 *
 * YAML is whitespace-significant and Flutter's manifest parser rejects the
 * whole file if the block is malformed, so this locates the existing block by
 * structure - the `  fonts:` key, then every line indented past it - rather
 * than by pattern-matching its contents. After the first run the markers are
 * present and the bounds are exact.
 */
const withFontsBlock = (pubspec: string, brand: Brand): string => {
  const rendered = renderPubspecFonts(brand.fonts);
  if (rendered.length === 0) {
    return pubspec;
  }
  const block = [
    FONTS_START,
    "  # Generated by packages/brand/apply.ts from packages/brand/brand.json - edit that, not this.",
    "  fonts:",
    rendered,
    FONTS_END,
  ].join("\n");

  const lines = pubspec.split("\n");

  const markerStart = lines.indexOf(FONTS_START);
  const markerEnd = lines.indexOf(FONTS_END);
  if (markerStart !== -1 && markerEnd > markerStart) {
    return [
      ...lines.slice(0, markerStart),
      block,
      ...lines.slice(markerEnd + 1),
    ].join("\n");
  }

  const keyIndex = lines.findIndex((line) => /^ {2}fonts:\s*$/.test(line));
  if (keyIndex === -1) {
    // No `fonts:` key at all. Appending one blind would land it outside the
    // `flutter:` mapping as often as not, so say so instead of guessing.
    return pubspec;
  }

  let end = keyIndex + 1;
  while (end < lines.length) {
    const line = lines[end] as string;
    if (line.trim().length === 0 || /^ {3,}/.test(line)) {
      end += 1;
      continue;
    }
    break;
  }

  return [...lines.slice(0, keyIndex), block, ...lines.slice(end)].join("\n");
};

const withConfigBlock = (pubspec: string, brand: Brand): string => {
  const block = configBlock(brand);
  const start = pubspec.indexOf(CONFIG_START);
  const end = pubspec.indexOf(CONFIG_END);
  if (start !== -1 && end !== -1) {
    return pubspec.slice(0, start) + block + pubspec.slice(end + CONFIG_END.length);
  }
  return `${pubspec.trimEnd()}\n\n${block}\n`;
};

/** Resolves a brand.json asset path, which is repo-relative. */
const resolveSource = async (
  ctx: Ctx,
  configured: string | null
): Promise<string | null> => {
  if (configured === null) {
    return null;
  }
  const absolute = join(ctx.root, configured);
  if (await Bun.file(absolute).exists()) {
    return absolute;
  }
  ctx.log.warn(
    `brand.json names "${configured}" but no such file exists - skipping the assets that depend on it.`
  );
  return null;
};

export const assets: Transform = {
  id: "70-assets",
  title: "Generate launcher icons, logos and launch imagery",
  needs: ["60-theme"],

  owns(): string[] {
    return [PUBSPEC];
  },

  async plan(ctx: Ctx): Promise<Change[]> {
    const changes: Change[] = [];
    const mobileDir = join(ctx.root, "apps/mobile");

    // --- Masters ---------------------------------------------------------
    let iconSource = await resolveSource(ctx, ctx.next.assets.iconSource);

    if (iconSource === null) {
      // No artwork: write a placeholder monogram so the fork still builds and
      // is visibly *not* upstream. packages/brand/TODO.md tells the user to replace it.
      const placeholder = join(ctx.root, `${GENERATED_DIR}/icon_placeholder.svg`);
      await Bun.write(placeholder, monogramSvg(ctx.next));
      iconSource = placeholder;
      ctx.log.warn(
        `no assets.iconSource in brand.json - generating a placeholder monogram. ` +
          `Drop real artwork at packages/brand/source/icon.png and re-run to replace it.`
      );
    } else {
      const meta = await probe(iconSource);
      if (meta.format !== "svg" && Math.min(meta.width, meta.height) < MIN_ICON_SOURCE) {
        throw new Error(
          `${ctx.next.assets.iconSource} is ${meta.width}x${meta.height}; the launcher icon master ` +
            `needs at least ${MIN_ICON_SOURCE}px on the short side (1024 preferred), or an SVG.`
        );
      }
    }

    const foregroundSource =
      (await resolveSource(ctx, ctx.next.assets.iconForeground)) ?? iconSource;
    const monochromeSource =
      (await resolveSource(ctx, ctx.next.assets.iconMonochrome)) ?? foregroundSource;

    // Masters are produced eagerly rather than as `Change`s: they are inputs to
    // the `dart run flutter_launcher_icons` step below, which needs them on
    // disk before it runs, and they live under packages/brand/ which the engine owns.
    if (!ctx.flags.dryRun) {
      const background = hexToCss(ctx.next.assets.iconBackgroundColor);
      await square(iconSource, join(ctx.root, ICON_MASTER), 1024, background);
      await square(foregroundSource, join(ctx.root, ICON_FOREGROUND), 1024);
      await monochrome(monochromeSource, join(ctx.root, ICON_MONOCHROME), 1024);

      // flutter_launcher_icons does not emit the Play Store listing asset.
      await square(iconSource, join(ctx.root, PLAY_STORE_ICON), 512, background);
    }
    ctx.log.info(`  icon masters -> ${GENERATED_DIR}/`);

    // --- Fonts -----------------------------------------------------------
    // The pubspec is the manifest for both icons and typefaces, and this
    // transform owns it, so the font work lives here rather than in `60-theme`
    // alongside the Dart side of the same change.
    for (const [family, sources] of Object.entries(ctx.next.fonts.files)) {
      for (const source of sources) {
        const absolute = join(ctx.root, source.path);
        if (!(await Bun.file(absolute).exists())) {
          throw new Error(
            `brand.json names the font file "${source.path}" for family "${family}", but it does not exist. ` +
              `Flutter renders an unknown family as the system face without an error, so this cannot be skipped.`
          );
        }
        const target = bundledFontPath(source);
        if (target !== source.path) {
          changes.push({
            kind: "write",
            path: target,
            contents: new Uint8Array(await Bun.file(absolute).arrayBuffer()),
            why: `bundle ${family}`,
          });
        }
      }
    }

    for (const orphan of orphanedFontFiles(ctx.next.fonts)) {
      if (ctx.files.exists(orphan)) {
        changes.push({
          kind: "delete",
          path: orphan,
          why: "fonts.replaceBundled: no declared family uses this face",
        });
      }
    }

    // --- pubspec ---------------------------------------------------------
    // This transform owns the pubspec, so the broad sweep skipped it - the
    // token rewrite has to happen here or the package name and the path
    // dependency on the recorder are left pointing at the old brand, and
    // `flutter pub get` fails on a package that no longer exists.
    const pubspec = await ctx.files.read(PUBSPEC);
    const updated = applyTokens(
      withFontsBlock(withConfigBlock(withLauncherIconsDep(pubspec), ctx.next), ctx.next),
      ctx.tokens
    ).text;
    if (updated !== pubspec) {
      changes.push({ kind: "write", path: PUBSPEC, contents: updated });
    }

    changes.push(
      {
        kind: "exec",
        cmd: ["flutter", "pub", "get"],
        cwd: mobileDir,
        why: "install flutter_launcher_icons",
      },
      {
        kind: "exec",
        cmd: ["dart", "run", "flutter_launcher_icons"],
        cwd: mobileDir,
        why: "generate every iOS and Android launcher icon density",
      }
    );

    // --- In-app logos ----------------------------------------------------
    //
    // These are the marks *inside* the app: the splash screen, the sign-in
    // sheet, the name-onboarding modal and the iOS launch screen. They used to
    // be regenerated only when `assets.logoLight`/`logoDark` were set
    // explicitly, which meant the common case - a fork supplying one icon -
    // shipped its own launcher icon and upstream's logo on every screen inside.
    // `derive()` now falls the logo back to the icon, and the last resort here
    // is the placeholder monogram, so upstream artwork never survives.
    //
    // 360px = the storyboard's 120pt LaunchLogo at @3x.
    const logoLight =
      (await resolveSource(ctx, ctx.next.assets.logoLight)) ?? iconSource;
    const logoDark =
      (await resolveSource(ctx, ctx.next.assets.logoDark)) ?? iconSource;

    if (!ctx.flags.dryRun) {
      for (const [source, targets] of [
        [
          logoLight,
          [LOGO_LIGHT, `${LAUNCH_LOGO_DIR}/logo_light.png`, README_LOGO_LIGHT],
        ],
        [
          logoDark,
          [LOGO_DARK, `${LAUNCH_LOGO_DIR}/logo_dark.png`, README_LOGO_DARK],
        ],
      ] as Array<[string, string[]]>) {
        for (const target of targets) {
          await square(source, join(ctx.root, target), 360);
        }
      }
    }

    if (logoDark === logoLight) {
      // Not an error - plenty of marks work on both - but it is the single most
      // common way a rebrand ships something invisible, and `brand:preview`
      // renders the mark on both backgrounds so it can be seen rather than
      // guessed at.
      ctx.log.warn(
        `assets.logoDark is the same artwork as the light one. If the mark is dark, it will be ` +
          `nearly invisible on the dark-mode splash and sign-in sheet - check \`bun run brand:preview\` ` +
          `and set assets.logoDark to a light-on-dark version if it needs one.`
      );
    }
    ctx.log.info("  in-app and launch-screen logos regenerated");

    // --- Splash texture --------------------------------------------------
    const texture = await resolveSource(ctx, ctx.next.assets.splashTexture);
    if (texture !== null && !ctx.flags.dryRun) {
      // Dimensions must match the <image> entry the storyboard caches.
      await resizeTo(
        texture,
        join(ctx.root, `${SPLASH_TEXTURE_DIR}/splash_texture.png`),
        1560,
        3376,
        "cover"
      );
      ctx.log.info("  splash texture regenerated at 1560x3376");
    }

    return changes;
  },
};

/**
 * Asserts that `flutter_launcher_icons` left the themed-icon layer intact.
 * It rewrites `mipmap-anydpi-v26/ic_launcher.xml` from scratch and drops the
 * `<monochrome>` node whenever `adaptive_icon_monochrome` is missing, which
 * degrades Android 13+ themed icons with no error anywhere.
 */
export const MONOCHROME_XML =
  "apps/mobile/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml";
