// GENERATED BY packages/brand/apply.ts - DO NOT EDIT.
// Edit packages/brand/brand.json and run `bun run brand:apply`.
//
// This file intentionally retains UPSTREAM branding. It is excluded from the
// rename engine (see NEVER_REWRITE in packages/brand/lib/fileindex.ts) so that the
// credit survives a rebrand instead of being renamed along with everything
// else. packages/brand/verify.ts asserts both directions: that the old brand name
// appears nowhere outside files like this one, and that it still appears here.

/// Credit to the upstream project this app is forked from.
class Attribution {
  const Attribution._();

  /// Set `attribution.enabled: false` in packages/brand/brand.json to hide the credit.
  /// Note that the licence still requires you to retain LICENSE and the
  /// copyright notice regardless of this flag.
  static const bool enabled = true;

  static const String upstreamName = "Stera";
  static const String upstreamOrg = "FPV Labs";
  static const String upstreamRepo = "https://github.com/fpv-labs/stera-app";

  /// Short credit line, shown in the profile footer.
  static const String text = "Powered by Stera";

  static const bool showInProfileFooter = true;
}
