// GENERATED BY packages/brand/apply.ts - DO NOT EDIT.
// Edit packages/brand/brand.json and run `bun run brand:apply`.

// The nullable constants below are nullable by contract, not by accident: the
// call sites are typed against them and must keep compiling whether or not a
// given fork sets the value. Dart only sees this file's initialisers, so it
// reads a populated one as a needlessly nullable declaration.
// ignore_for_file: unnecessary_nullable_for_final_variable_declarations

/// Brand-specific strings and links.
///
/// Every user-visible mention of the product name, and every outbound link,
/// resolves through here. Nothing else in `lib/` should contain a brand
/// literal - if you find one, it belongs in this file and in packages/brand/brand.json.
class Brand {
  const Brand._();

  /// Product name, as shown in the UI.
  static const String appName = "RootLens";

  /// Short form, for space-constrained surfaces such as the launcher label.
  static const String appNameShort = "RootLens";

  /// `MaterialApp.title` - what the OS task switcher shows.
  static const String appTitle = "RootLens";

  /// One-line positioning statement.
  static const String tagline = "Egocentric data capture for embodied AI";

  /// Splash headline and the line beneath it.
  static const String splashTitle = "RootLens";
  static const String splashSubtitle = "Powered by Stera";

  /// Longer marketing copy on the sign-in sheet.
  static const String loginTagline = "Egocentric data capture for embodied AI";

  /// Legal entity behind the app.
  static const String legalEntity = "RootLens";

  // --- Links -------------------------------------------------------------

  static const String website = "https://rootlens.io";
  static const String termsAndConditions = "https://rootlens.io/terms";
  static const String privacyPolicy = "https://rootlens.io/privacy";
  static const String contactEmail = "contact@rootlens.io";

  /// Null when the fork does not run a Discord.
  static const String? discordInvite = null;

  static const String sourceRepo = "https://github.com/yudai-mori-2004/stera-app";

  // --- Updates -----------------------------------------------------------

  /// Where the in-app updater looks for a newer version, and where "Update now"
  /// sends the user. All three are null when the fork has not published
  /// anywhere - the update check is then skipped and nothing is fetched.
  ///
  /// [updateFeedUrl] is a Sparkle-style appcast and wins over the store
  /// listings on both platforms.
  static const String? playStoreUrl = null;
  static const String? appStoreUrl = null;
  static const String? updateFeedUrl = null;

  /// Reverse-DNS application identifier, shared by both platforms.
  static const String bundleId = "io.rootlens.app";
}
