// GENERATED BY packages/brand/apply.ts - DO NOT EDIT.
// Edit packages/brand/brand.json and run `bun run brand:apply`.

/// The four typeface roles.
///
/// `app_text_theme.dart` names these instead of literal family strings, so a
/// fork changes its typography in packages/brand/brand.json rather than in
/// twenty `TextStyle`s. Every family named here is declared in
/// `apps/mobile/pubspec.yaml`; the engine refuses to write a family that is
/// not, because Flutter falls back to the system face for an unknown family
/// without reporting an error.
class BrandFonts {
  const BrandFonts._();

  /// Headlines and the splash wordmark.
  static const String display = "EBGaramond";

  /// Body copy and UI labels - by far the most used.
  static const String body = "Geist";

  /// Numerals, timestamps, identifiers.
  static const String mono = "GeistMono";

  /// The character face, used sparingly for large display numerals.
  static const String accent = "Handjet";
}
