// GENERATED BY packages/brand/apply.ts - DO NOT EDIT.
// Edit packages/brand/brand.json and run `bun run brand:apply`.

/// The spacing scale.
///
/// Density: `default`. Change it in packages/brand/brand.json under
/// `theme.space`, or override an individual step under `theme.space.scale`.
///
/// Every gap and every pad in the app is on this scale. Density is the axis
/// that survives a palette swap: two apps sharing a colour, a corner radius and
/// a typeface still read as different products when one breathes and the other
/// is packed.
///
/// Reach for these through `AppSpacing`, which wraps them as ready-made
/// `EdgeInsets`, rather than importing this file.
class BrandSpace {
  const BrandSpace._();

  /// No gap. Zero in every density - the absence of spacing, not a small amount of it.
  static const double none = 0;

  /// Hairline separation: an icon from its label.
  static const double xxs = 2;

  /// Tight pairs inside a control.
  static const double xs = 4;

  /// Chip and badge padding.
  static const double xsPlus = 6;

  /// The small gap: between a title and its subtitle.
  static const double sm = 8;

  /// Compact list rows.
  static const double smPlus = 10;

  /// Between related elements in a card.
  static const double md = 12;

  /// Card padding on dense screens.
  static const double mdPlus = 14;

  /// The workhorse: screen margins and card padding.
  static const double lg = 16;

  /// Between sections of a form.
  static const double lgPlus = 20;

  /// Between major sections.
  static const double xl = 24;

  /// Above a primary action.
  static const double xlPlus = 28;

  /// Screen-level breathing room.
  static const double xxl = 32;

  /// Empty-state and hero spacing.
  static const double huge = 64;
}
