// GENERATED BY packages/brand/apply.ts - DO NOT EDIT.
// Edit packages/brand/brand.json and run `bun run brand:apply`.

import "package:flutter/painting.dart";

/// The typographic scale.
///
/// Style: `default`. Change it in packages/brand/brand.json under
/// `theme.type`, override an individual step under `theme.type.scale`, or
/// move the weights under `theme.type.weights`.
///
/// `app_text_theme.dart` is built entirely from these, so the ramp is part of
/// the brand rather than forty literal `fontSize:`s. Two apps in the same
/// typeface still read as different products when this table differs, which is
/// why changing `fonts.body` alone never made a fork look like its own thing.
///
/// Reach for these through `AppType` or `context.textTheme` rather than
/// importing this file.
class BrandType {
  const BrandType._();

  /// 10px on 14px.
  static const double sizeXs = 10;
  static const double heightXs = 14 / 10;

  /// 12px on 16px.
  static const double sizeSm = 12;
  static const double heightSm = 16 / 12;

  /// 14px on 20px.
  static const double sizeMd = 14;
  static const double heightMd = 20 / 14;

  /// 16px on 24px.
  static const double sizeLg = 16;
  static const double heightLg = 24 / 16;

  /// 18px on 26px.
  static const double sizeXl = 18;
  static const double heightXl = 26 / 18;

  /// 20px on 20px.
  static const double sizeXl2 = 20;
  static const double heightXl2 = 20 / 20;

  /// 24px on 24px.
  static const double sizeXl3 = 24;
  static const double heightXl3 = 24 / 24;

  /// 28px on 28px.
  static const double sizeXl3Plus = 28;
  static const double heightXl3Plus = 28 / 28;

  /// 32px on 32px.
  static const double sizeXl4 = 32;
  static const double heightXl4 = 32 / 32;

  /// Body copy.
  static const FontWeight weightRegular = FontWeight.w400;

  /// Emphasised body, secondary labels.
  static const FontWeight weightMedium = FontWeight.w500;

  /// Headings and interactive labels.
  static const FontWeight weightSemibold = FontWeight.w600;

  /// Page titles and the display sizes.
  static const FontWeight weightBold = FontWeight.w700;
}
