// GENERATED BY packages/brand/apply.ts - DO NOT EDIT.
// Edit packages/brand/brand.json and run `bun run brand:apply`.

import "package:flutter/material.dart";

/// Every colour token, resolved from packages/brand/brand.json.
///
/// `colors.dart` reads from here rather than carrying literals, which is what
/// makes the palette reachable from a config file at all. Values come from the
/// accent, then the tint, then `theme.overrides` - each stage able to overrule
/// the one before it.
///
/// No tint: the neutral tokens are upstream's, unchanged.
class BrandPalette {
  const BrandPalette._();

  // --- Text --------------------------------------------------------------

  /// `C.textPrimary`
  static const Color textPrimaryLight = Color(0xFF18191B);
  static const Color textPrimaryDark = Color(0xFFFFFFFF);

  /// `C.textSecondary`
  static const Color textSecondaryLight = Color(0xFF737373);
  static const Color textSecondaryDark = Color(0xFFBBBEC3);

  /// `C.textTertiary`
  static const Color textTertiaryLight = Color(0xFFBBBEC3);
  static const Color textTertiaryDark = Color(0xFF737373);

  /// `C.textInversePrimary`
  static const Color textInversePrimaryLight = Color(0xFFFFFFFF);
  static const Color textInversePrimaryDark = Color(0xFF18191B);

  /// `C.textInverseSecondary`
  static const Color textInverseSecondaryLight = Color(0x99FFFFFF);
  static const Color textInverseSecondaryDark = Color(0x9918191B);

  /// `C.textDisabled`
  static const Color textDisabledLight = Color(0xFFC7C7C7);
  static const Color textDisabledDark = Color(0xFF5C5C5C);

  /// `C.textAlert`
  static const Color textAlertLight = Color(0xFFB27700);
  static const Color textAlertDark = Color(0xFFFFB740);

  /// `C.textDestructive`
  static const Color textDestructiveLight = Color(0xFFD32F2F);
  static const Color textDestructiveDark = Color(0xFFEF5350);

  // --- Surface -----------------------------------------------------------

  /// `C.surfacePrimary`
  static const Color surfacePrimaryLight = Color(0xFFF8F9FA);
  static const Color surfacePrimaryDark = Color(0xFF18191B);

  /// `C.surfaceSecondary`
  static const Color surfaceSecondaryLight = Color(0xFFFFFFFF);
  static const Color surfaceSecondaryDark = Color(0xFF232426);

  /// `C.surfaceTertiary`
  static const Color surfaceTertiaryLight = Color(0xFFF7F4ED);
  static const Color surfaceTertiaryDark = Color(0xFF2E2F31);

  /// `C.surfaceBlack`
  static const Color surfaceBlackLight = Color(0xFF18191B);
  static const Color surfaceBlackDark = Color(0xFF000000);

  /// `C.surfaceWhite`
  static const Color surfaceWhiteLight = Color(0xFFFFFFFF);
  static const Color surfaceWhiteDark = Color(0xFFFFFFFF);

  // --- Border ------------------------------------------------------------

  /// `C.borderDefault`
  static const Color borderDefaultLight = Color(0xFFB7B7B7);
  static const Color borderDefaultDark = Color(0xFF5C5C5C);

  /// `C.borderDisabled`
  static const Color borderDisabledLight = Color(0xFFC7C7C7);
  static const Color borderDisabledDark = Color(0xFF3D3D3D);

  /// `C.borderDivider`
  static const Color borderDividerLight = Color(0xFFE0E0E0);
  static const Color borderDividerDark = Color(0xFF3D3D3D);

  /// `C.borderError`
  static const Color borderErrorLight = Color(0xFFD32F2F);
  static const Color borderErrorDark = Color(0xFFEF5350);

  /// `C.borderSelected`
  static const Color borderSelectedLight = Color(0xFF000000);
  static const Color borderSelectedDark = Color(0xFFFFFFFF);

  // --- Icon --------------------------------------------------------------

  /// `C.iconPrimary`
  static const Color iconPrimaryLight = Color(0xFF737373);
  static const Color iconPrimaryDark = Color(0xFFBBBEC3);

  /// `C.iconDisabled`
  static const Color iconDisabledLight = Color(0xFFC7C7C7);
  static const Color iconDisabledDark = Color(0xFF5C5C5C);

  // --- Neutral -----------------------------------------------------------

  /// `C.neutralDarkGray`
  static const Color neutralDarkGrayLight = Color(0xFF737373);
  static const Color neutralDarkGrayDark = Color(0xFF8E8E93);

  /// `C.neutralGray`
  static const Color neutralGrayLight = Color(0xFFBBBEC3);
  static const Color neutralGrayDark = Color(0xFFBBBEC3);

  /// `C.neutralLightGray`
  static const Color neutralLightGrayLight = Color(0xFFEBEBEB);
  static const Color neutralLightGrayDark = Color(0xFF3D3D3D);

  /// `C.neutralBlack`
  static const Color neutralBlackLight = Color(0xFF18191B);
  static const Color neutralBlackDark = Color(0xFF000000);

  /// `C.neutralWhite`
  static const Color neutralWhiteLight = Color(0xFFFFFFFF);
  static const Color neutralWhiteDark = Color(0xFFFFFFFF);

  // --- Semantic ----------------------------------------------------------

  /// `C.blue`
  static const Color blueLight = Color(0xFF007AFF);
  static const Color blueDark = Color(0xFF0A84FF);

  /// `C.red`
  static const Color redLight = Color(0xFFD32F2F);
  static const Color redDark = Color(0xFFEF5350);

  /// `C.green`
  static const Color greenLight = Color(0xFF047A00);
  static const Color greenDark = Color(0xFF32D74B);

  /// `C.yellow`
  static const Color yellowLight = Color(0xFFFFB740);
  static const Color yellowDark = Color(0xFFFFB740);

  // --- Brand -------------------------------------------------------------

  /// `C.brandAccent`
  static const Color brandAccentLight = Color(0xFF25528E);
  static const Color brandAccentDark = Color(0xFF336AB3);

  // --- Aliases --------------------------------------------------------

  /// Kept so that a tree rebranded by an earlier version of the engine - where
  /// `colors.dart` referenced `accentLight` directly - still compiles.
  static const Color accentLight = brandAccentLight;
  static const Color accentDark = brandAccentDark;

  // --- Launch screen --------------------------------------------------

  /// These must stay in sync with the iOS `LaunchBackground` /
  /// `LaunchForeground` colour sets, which the engine regenerates from the
  /// same values.
  static const Color launchBackgroundLight = Color(0xFFF7F4ED);
  static const Color launchBackgroundDark = Color(0xFF2E2F31);
  static const Color launchForegroundLight = Color(0xFF18191B);
  static const Color launchForegroundDark = Color(0xFFFFFFFF);
}
