// GENERATED BY packages/brand/apply.ts - DO NOT EDIT.
// Edit packages/brand/brand.json and run `bun run brand:apply`.

/// The corner-radius scale.
///
/// Style: `soft`. Change it in packages/brand/brand.json under
/// `theme.shape`, or override an individual step under `theme.shape.scale`.
///
/// The widget tree references these instead of literal radii, so the app's
/// silhouette is part of the brand rather than something hard-coded in 180
/// places. Every radius in the app is on this scale - there are no off-scale
/// one-offs left, which is what makes a shape style reach the whole product
/// rather than just the widgets that happened to use round numbers.
///
/// Reach for these through `context.radii` rather than importing this file:
/// `AppRadii` wraps them as ready-made `BorderRadius` values.
class BrandShape {
  const BrandShape._();

  /// Grabbers, progress bars, hairline indicators.
  static const double radiusHairline = 1.5;

  /// Chips, badges, small inputs.
  static const double radiusXs = 4;

  /// Small chips and inline pills.
  static const double radiusXsPlus = 6;

  /// Buttons, list rows, thumbnails.
  static const double radiusSm = 8;

  /// Compact cards and banners.
  static const double radiusSmPlus = 10;

  /// The workhorse: cards, sheets, most containers.
  static const double radiusMd = 12;

  /// Cards that sit above other cards.
  static const double radiusMdPlus = 14;

  /// Large cards and modals.
  static const double radiusLg = 16;

  /// Bottom sheet tops and full-width panels.
  static const double radiusLgPlus = 20;

  /// Hero panels.
  static const double radiusXl = 24;

  /// Stadium-ish buttons that are not quite pills.
  static const double radiusXlPlus = 30;

  /// Avatars and pill buttons. A sentinel meaning "clamp to half the shorter
  /// side" - it is not scaled by the style, because "sharp" should not turn a
  /// circular avatar into a rounded square.
  static const double radiusFull = 999;
}
