/**
 * The set of files the engine is allowed to touch.
 *
 * Built from `git ls-files`, never a filesystem walk. A walk would descend into
 * `apps/mobile/build/`, `.dart_tool/`, `ios/Pods/` and `node_modules/`, which
 * between them contain tens of thousands of files carrying the brand token -
 * rewriting any of them is at best wasted work and at worst corrupts a cache
 * that then gets copied into a build.
 */

import { join } from "node:path";

import type { FileIndex } from "./types.ts";

/**
 * Paths that must never be text-substituted, even though they are tracked.
 *
 * Two different reasons live in this list, and it is worth keeping them
 * straight:
 *
 * - **Regenerated, not rewritten.** Lockfiles are derived artefacts. Editing
 *   `bun.lock` textually is how you turn `sisteransi` into garbage; the engine
 *   re-runs `bun install` / `flutter pub get` instead.
 * - **Legally or semantically must survive.** LICENSE files carry the upstream
 *   copyright notice, which Apache 2.0 requires be retained. Changelogs are a
 *   historical record. The attribution files exist precisely to keep saying
 *   "Stera" after everything else has stopped.
 */
export const NEVER_REWRITE: readonly RegExp[] = [
  // Regenerated by the lockfile transform.
  /^bun\.lock$/,
  /(^|\/)package-lock\.json$/,
  /(^|\/)yarn\.lock$/,
  /(^|\/)pnpm-lock\.yaml$/,
  /(^|\/)pubspec\.lock$/,
  /(^|\/)Podfile\.lock$/,
  /(^|\/)Package\.resolved$/,
  /(^|\/)gradle\.lockfile$/,

  // Must retain upstream text.
  /(^|\/)LICENSE(\.[A-Za-z]+)?$/,
  /(^|\/)LICENCE(\.[A-Za-z]+)?$/,
  /(^|\/)NOTICE$/,
  // The font licence has to travel with the fonts verbatim - OFL 1.1 § 2.
  /(^|\/)OFL\.txt$/,
  /(^|\/)CHANGELOG\.md$/,
  /(^|\/)ATTRIBUTION\.md$/,
  /(^|\/)attribution\.dart$/,

  // The engine's own tree. Rewriting `UPSTREAM_BRAND` mid-run would be a
  // spectacular way to make run 2 unreproducible.
  /^packages\/brand\//,

  // Never tracked in practice, but cheap insurance if someone commits them.
  /(^|\/)build\//,
  /(^|\/)\.dart_tool\//,
  /(^|\/)Pods\//,
  /(^|\/)node_modules\//,
  /(^|\/)\.git\//,
  /(^|\/)DerivedData\//,
];

/** Extensions whose bytes are not text and must not go through the tokenizer. */
export const BINARY_EXTENSIONS: ReadonlySet<string> = new Set([
  "png", "jpg", "jpeg", "gif", "webp", "ico", "icns", "bmp", "tiff",
  "ttf", "otf", "woff", "woff2", "eot",
  "mp3", "mp4", "mov", "wav", "m4a", "aac",
  "zip", "gz", "tgz", "jar", "aar", "so", "dylib", "a", "o",
  "pdf", "keystore", "jks", "p12", "mobileprovision",
  "mcap", "bin", "dat", "wasm",
]);

const extensionOf = (path: string): string => {
  const base = path.slice(path.lastIndexOf("/") + 1);
  const dot = base.lastIndexOf(".");
  return dot <= 0 ? "" : base.slice(dot + 1).toLowerCase();
};

export const isNeverRewrite = (path: string): boolean =>
  NEVER_REWRITE.some((pattern) => pattern.test(path));

export const isBinary = (path: string): boolean =>
  BINARY_EXTENSIONS.has(extensionOf(path));

export const isRewritable = (path: string): boolean =>
  !(isNeverRewrite(path) || isBinary(path));

export const listTrackedFiles = async (root: string): Promise<string[]> => {
  const proc = Bun.spawn(["git", "ls-files", "-z"], {
    cwd: root,
    stdout: "pipe",
    stderr: "pipe",
  });
  const [out, err, code] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited,
  ]);
  if (code !== 0) {
    throw new Error(`git ls-files failed in ${root}: ${err.trim()}`);
  }
  return out.split("\0").filter((entry) => entry.length > 0);
};

export const createFileIndex = async (root: string): Promise<FileIndex> => {
  const tracked = await listTrackedFiles(root);
  const trackedSet = new Set(tracked);
  const rewritable = tracked.filter(isRewritable);
  const cache = new Map<string, string>();

  return {
    all: () => tracked,
    rewritable: () => rewritable,
    under: (prefix) => tracked.filter((path) => path.startsWith(prefix)),
    exists: (path) => trackedSet.has(path),
    read: async (path) => {
      const cached = cache.get(path);
      if (cached !== undefined) {
        return cached;
      }
      const text = await Bun.file(join(root, path)).text();
      cache.set(path, text);
      return text;
    },
  };
};
