import { describe, expect, test } from "bun:test";

import { derive } from "./derive.ts";
import {
  buildAttributionDart,
  buildBrandDart,
  buildBrandFontsDart,
  buildBrandPaletteDart,
  buildBrandShapeDart,
  buildColorsetJson,
  patchColorsDart,
  patchInfoPlist,
  patchStoryboard,
  patchStringsXml,
} from "./generate.ts";
import { TOKEN_NAMES } from "./palette.ts";
import { applyTokens, buildTokens } from "./tokens.ts";
import { UPSTREAM_BRAND } from "./upstream.ts";

const ACME = derive({
  brand: { name: "Acme Vision", legalEntity: "Acme Robotics, Inc." },
  identifiers: { bundleId: "com.acmerobotics.vision" },
  urls: {
    website: "https://acmerobotics.com",
    contactEmail: "hello@acmerobotics.com",
    sourceRepo: "https://github.com/acme-robotics/acme-vision",
  },
  theme: { brandAccentLight: "#3D8AE8", brandAccentDark: "#40A0FF" },
});

describe("brand.dart", () => {
  const out = buildBrandDart(ACME);

  test("carries the do-not-edit header", () => {
    expect(out).toContain("GENERATED BY packages/brand/apply.ts - DO NOT EDIT.");
  });

  test("emits the resolved values", () => {
    expect(out).toContain('static const String appName = "Acme Vision";');
    expect(out).toContain('static const String appTitle = "Acme Vision by Acme Robotics, Inc.";');
  });

  test("an unpublished fork gets no update urls, so the updater stays off", () => {
    expect(out).toContain("static const String? playStoreUrl = null;");
    expect(out).toContain("static const String? appStoreUrl = null;");
    expect(out).toContain("static const String? updateFeedUrl = null;");
  });

  test("update urls are built from the store ids and the feed", () => {
    const published = buildBrandDart(
      derive({
        brand: { name: "Acme Vision" },
        identifiers: { bundleId: "com.acmerobotics.vision" },
        urls: {
          website: "https://acmerobotics.com",
          contactEmail: "hello@acmerobotics.com",
          sourceRepo: "https://github.com/acme-robotics/acme-vision",
          playStoreAppId: "com.acmerobotics.vision",
          appStoreId: "6501234567",
          updateFeed: "https://acmerobotics.com/appcast.xml",
        },
      })
    );
    expect(published).toContain(
      'static const String? playStoreUrl = "https://play.google.com/store/apps/details?id=com.acmerobotics.vision";'
    );
    expect(published).toContain(
      'static const String? appStoreUrl = "https://apps.apple.com/app/id6501234567";'
    );
    expect(published).toContain(
      'static const String? updateFeedUrl = "https://acmerobotics.com/appcast.xml";'
    );
  });

  test("a null discord invite stays null, not an empty string", () => {
    expect(out).toContain("static const String? discordInvite = null;");
  });

  test("escapes quotes and dollar signs so generated Dart cannot break out", () => {
    const risky = derive({
      brand: { name: 'Ac"me $Vision' },
      identifiers: { bundleId: "com.acmerobotics.vision" },
      urls: {
        website: "https://acmerobotics.com",
        contactEmail: "hello@acmerobotics.com",
        sourceRepo: "https://github.com/acme-robotics/acme-vision",
      },
    });
    const text = buildBrandDart(risky);
    expect(text).toContain('\\"me');
    expect(text).toContain("\\$Vision");
  });
});

describe("brand_palette.dart", () => {
  test("emits Flutter colour literals", () => {
    const out = buildBrandPaletteDart(ACME);
    expect(out).toContain("static const Color brandAccentLight = Color(0xFF3D8AE8);");
    expect(out).toContain("static const Color brandAccentDark = Color(0xFF40A0FF);");
  });

  test("keeps the accent aliases a tree rebranded by an older engine still uses", () => {
    const out = buildBrandPaletteDart(ACME);
    expect(out).toContain("static const Color accentLight = brandAccentLight;");
    expect(out).toContain("static const Color accentDark = brandAccentDark;");
  });

  test("emits every token, not just the accent", () => {
    const out = buildBrandPaletteDart(ACME);
    for (const token of TOKEN_NAMES) {
      expect(out).toContain(`static const Color ${token}Light = Color(0x`);
      expect(out).toContain(`static const Color ${token}Dark = Color(0x`);
    }
  });

  test("an untinted brand leaves the neutral tokens exactly as upstream", () => {
    const out = buildBrandPaletteDart(ACME);
    expect(out).toContain("static const Color surfacePrimaryLight = Color(0xFFF8F9FA);");
    expect(out).toContain("static const Color textPrimaryLight = Color(0xFF18191B);");
  });

  test("includes theme overrides when present", () => {
    const withOverride = derive({
      brand: { name: "Acme Vision" },
      identifiers: { bundleId: "com.acmerobotics.vision" },
      urls: {
        website: "https://acmerobotics.com",
        contactEmail: "hello@acmerobotics.com",
        sourceRepo: "https://github.com/acme-robotics/acme-vision",
      },
      theme: { overrides: { textPrimary: { light: "#111111", dark: "#EEEEEE" } } },
    });
    const out = buildBrandPaletteDart(withOverride);
    expect(out).toContain("static const Color textPrimaryLight = Color(0xFF111111);");
    expect(out).toContain("static const Color textPrimaryDark = Color(0xFFEEEEEE);");
  });
});

describe("attribution survives the rename", () => {
  // The bug this locks in: generating the credit and *then* running the token
  // engine over it produced "Powered by Acme Vision - built on Acme Vision",
  // which is precisely what attribution exists to prevent.
  const rules = buildTokens(UPSTREAM_BRAND, ACME);

  test("attribution.dart still names the upstream project", () => {
    const out = buildAttributionDart(ACME);
    expect(out).toContain('static const String upstreamName = "Stera";');
    expect(out).toContain('static const String upstreamOrg = "FPV Labs";');
    expect(out).toContain('static const String text = "Powered by Stera";');
  });

  test("running the token engine over it WOULD destroy it", () => {
    // Demonstrates why attribution.dart is on the never-rewrite list rather
    // than relying on anyone remembering not to touch it.
    const rewritten = applyTokens(buildAttributionDart(ACME), rules).text;
    expect(rewritten).not.toContain('"Powered by Stera"');
  });
});

describe("native copy patches", () => {
  test("strings.xml sets both names and leaves the Google client id alone", () => {
    const xml = `<resources>
    <string name="default_web_client_id">000000000000-abc.apps.googleusercontent.com</string>
    <string name="app_name">Stera</string>
    <string name="app_name_short">Stera</string>
</resources>`;
    const out = patchStringsXml(xml, ACME);
    expect(out).toContain('<string name="app_name">Acme Vision</string>');
    expect(out).toContain('<string name="app_name_short">Acme</string>');
    // Owned by tool/sync_google_client_ids.dart, not by the rebrand engine.
    expect(out).toContain("000000000000-abc.apps.googleusercontent.com");
  });

  test("Info.plist gets names and all six usage descriptions", () => {
    const plist = `<dict>
\t<key>CFBundleDisplayName</key>
\t<string>Stera</string>
\t<key>CFBundleName</key>
\t<string>Stera</string>
\t<key>NSCameraUsageDescription</key>
\t<string>FPV Labs uses your camera to record
and capture video.</string>
\t<key>NSMotionUsageDescription</key>
\t<string>FPV Labs uses motion sensors.</string>
\t<key>NSPhotoLibraryUsageDescription</key>
\t<string>FPV Labs needs your library.</string>
\t<key>NSPhotoLibraryAddUsageDescription</key>
\t<string>FPV Labs saves videos.</string>
\t<key>NSMicrophoneUsageDescription</key>
\t<string>Voice commands.</string>
\t<key>NSSpeechRecognitionUsageDescription</key>
\t<string>Voice commands.</string>
</dict>`;
    const out = patchInfoPlist(plist, ACME);
    expect(out).toContain("<string>Acme Vision</string>");
    expect(out).toContain("<string>Acme</string>");
    expect(out).toContain("Acme Vision uses your camera");
    expect(out).not.toContain("FPV Labs");
    // The multi-line original must be fully replaced, not partly.
    expect(out).not.toContain("and capture video.");
  });

  test("storyboard labels and named colours are patched", () => {
    const xml = `<label text="Stera" id="Ste-la-bl1"/>
<label text="by FPV Labs" id="Fpv-la-bl2"/>
<namedColor name="LaunchBackground">
    <color red="0.9" green="0.9" blue="0.9" alpha="1"/>
</namedColor>`;
    const out = patchStoryboard(xml, ACME);
    expect(out).toContain('text="Acme Vision"');
    expect(out).toContain('text="by Acme Robotics, Inc."');
    expect(out).toContain('<namedColor name="LaunchBackground">');
    expect(out).toContain('red="0.969"');
  });
});

describe("colour sets", () => {
  test("emit light plus a dark-appearance entry in sRGB", () => {
    const parsed = JSON.parse(buildColorsetJson("0xFFF7F4ED", "0xFF2E2F31")) as {
      colors: Array<{
        appearances?: unknown[];
        color: { components: Record<string, string> };
      }>;
    };
    expect(parsed.colors).toHaveLength(2);
    expect(parsed.colors[0]?.appearances).toBeUndefined();
    expect(parsed.colors[0]?.color.components.red).toBe("0.969");
    expect(parsed.colors[1]?.appearances).toEqual([
      { appearance: "luminosity", value: "dark" },
    ]);
    expect(parsed.colors[1]?.color.components.red).toBe("0.180");
  });
});

describe("colors.dart rewrite", () => {
  // A miniature of the real file: two factories, the same token names in each,
  // and a shared gradient block that must survive untouched.
  const SOURCE = `import "package:acme_vision/src/core/theme/colors.dart";

class C {
  final LinearGradient goldGradient = const LinearGradient(
    colors: [Color(0xFFFDCD24), Color(0xFFCF6D0A)],
  );

  C({required this.textPrimary, required this.surfaceWhite});

  factory C.light() {
    return C(
      textPrimary: const Color(0xFF18191B),
      surfaceWhite: const Color(0xFFFFFFFF),
    );
  }

  factory C.dark() {
    return C(
      textPrimary: const Color(0xFFFFFFFF),
      surfaceWhite: const Color(0xFFFFFFFF),
    );
  }
}`;

  test("routes each factory's literals to the matching mode", () => {
    const patch = patchColorsDart(SOURCE, UPSTREAM_BRAND);
    expect(patch.text).toContain("textPrimary: BrandPalette.textPrimaryLight,");
    expect(patch.text).toContain("textPrimary: BrandPalette.textPrimaryDark,");
    expect(patch.rewritten).toBe(4);
  });

  test("disambiguates tokens that share a literal in one mode", () => {
    // textInversePrimary and surfaceWhite are both 0xFFFFFFFF in light mode;
    // splitting on `factory C.dark()` is what keeps them apart.
    const patch = patchColorsDart(SOURCE, UPSTREAM_BRAND);
    expect(patch.text).toContain("surfaceWhite: BrandPalette.surfaceWhiteLight,");
    expect(patch.text).toContain("surfaceWhite: BrandPalette.surfaceWhiteDark,");
  });

  test("leaves the shared gradients and the constructor alone", () => {
    const patch = patchColorsDart(SOURCE, UPSTREAM_BRAND);
    expect(patch.text).toContain("colors: [Color(0xFFFDCD24), Color(0xFFCF6D0A)]");
    expect(patch.text).toContain("C({required this.textPrimary, required this.surfaceWhite});");
  });

  test("is idempotent", () => {
    const once = patchColorsDart(SOURCE, UPSTREAM_BRAND);
    const twice = patchColorsDart(once.text, UPSTREAM_BRAND);
    expect(twice.text).toBe(once.text);
    expect(twice.rewritten).toBe(0);
  });

  test("reports a hand-edited colour rather than silently reverting it", () => {
    const edited = SOURCE.replace("0xFF18191B", "0xFF102030");
    const patch = patchColorsDart(edited, UPSTREAM_BRAND);
    expect(patch.drifted).toHaveLength(1);
    expect(patch.drifted[0]).toContain("textPrimary (light)");
  });

  test("a file without the dark factory is left untouched", () => {
    const patch = patchColorsDart("class C {}", UPSTREAM_BRAND);
    expect(patch.rewritten).toBe(0);
    expect(patch.text).toBe("class C {}");
  });
});

describe("brand_shape.dart", () => {
  test("emits the scale for the chosen style", () => {
    const rounded = derive({
      brand: { name: "Acme Vision" },
      identifiers: { bundleId: "com.acmerobotics.vision" },
      urls: {
        website: "https://acmerobotics.com",
        contactEmail: "hello@acmerobotics.com",
        sourceRepo: "https://github.com/acme-robotics/acme-vision",
      },
      theme: { shape: { style: "rounded" } },
    });
    const out = buildBrandShapeDart(rounded);
    expect(out).toContain("static const double radiusMd = 18;");
    expect(out).toContain("Style: `rounded`");
  });

  test("defaults to the upstream geometry, so applying changes no pixels", () => {
    const out = buildBrandShapeDart(ACME);
    expect(out).toContain("static const double radiusXs = 4;");
    expect(out).toContain("static const double radiusSm = 8;");
    expect(out).toContain("static const double radiusMd = 12;");
    expect(out).toContain("static const double radiusLg = 16;");
    expect(out).toContain("static const double radiusXl = 24;");
  });

  test("never scales the full sentinel", () => {
    for (const style of ["sharp", "soft", "rounded", "pill"] as const) {
      const brand = derive({
        brand: { name: "Acme Vision" },
        identifiers: { bundleId: "com.acmerobotics.vision" },
        urls: {
          website: "https://acmerobotics.com",
          contactEmail: "hello@acmerobotics.com",
          sourceRepo: "https://github.com/acme-robotics/acme-vision",
        },
        theme: { shape: { style } },
      });
      expect(buildBrandShapeDart(brand)).toContain("static const double radiusFull = 999;");
    }
  });
});

describe("brand_fonts.dart", () => {
  test("emits the four roles", () => {
    const out = buildBrandFontsDart(ACME);
    expect(out).toContain('static const String display = "EBGaramond";');
    expect(out).toContain('static const String body = "Geist";');
    expect(out).toContain('static const String mono = "GeistMono";');
    expect(out).toContain('static const String accent = "Handjet";');
  });

  test("carries the do-not-edit header", () => {
    expect(buildBrandFontsDart(ACME)).toContain("DO NOT EDIT");
  });
});
