/**
 * Builders for the files the engine owns outright.
 *
 * Every one carries a DO-NOT-EDIT header and is rewritten wholesale on each
 * run. That is what makes runs 2..N cheap and safe: once the seams are
 * installed, a rebrand is mostly "regenerate three Dart files", not "regex
 * thirty source files again and hope".
 */

import { hexToRgba } from "./color.ts";
import { MAX_TINT, TOKEN_GROUPS, TOKEN_NAMES } from "./palette.ts";
import { SPACE_STEPS } from "./space.ts";
import { TYPE_STEPS } from "./type.ts";
import type { Brand, Hex } from "./types.ts";

export const GENERATED_HEADER = [
  "// GENERATED BY packages/brand/apply.ts - DO NOT EDIT.",
  "// Edit packages/brand/brand.json and run `bun run brand:apply`.",
].join("\n");

const dartString = (value: string): string =>
  `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\$/g, "\\$")}"`;

const dartColor = (hex: Hex): string => `Color(${hex})`;

// ---------------------------------------------------------------------------
// apps/mobile/lib/src/core/config/constants/brand.dart
// ---------------------------------------------------------------------------

export const BRAND_DART_PATH =
  "apps/mobile/lib/src/core/config/constants/brand.dart";

export const buildBrandDart = (brand: Brand): string => {
  const { copy, urls, identifiers } = brand;
  const discord =
    urls.discordInvite === null ? "null" : dartString(urls.discordInvite);
  const playStoreUrl =
    urls.playStoreAppId === null
      ? "null"
      : dartString(
          `https://play.google.com/store/apps/details?id=${urls.playStoreAppId}`
        );
  const appStoreUrl =
    urls.appStoreId === null
      ? "null"
      : dartString(`https://apps.apple.com/app/id${urls.appStoreId}`);
  const updateFeedUrl =
    urls.updateFeed === null ? "null" : dartString(urls.updateFeed);

  return `${GENERATED_HEADER}

// The nullable constants below are nullable by contract, not by accident: the
// call sites are typed against them and must keep compiling whether or not a
// given fork sets the value. Dart only sees this file's initialisers, so it
// reads a populated one as a needlessly nullable declaration.
// ignore_for_file: unnecessary_nullable_for_final_variable_declarations

/// Brand-specific strings and links.
///
/// Every user-visible mention of the product name, and every outbound link,
/// resolves through here. Nothing else in \`lib/\` should contain a brand
/// literal - if you find one, it belongs in this file and in packages/brand/brand.json.
class Brand {
  const Brand._();

  /// Product name, as shown in the UI.
  static const String appName = ${dartString(copy.appName)};

  /// Short form, for space-constrained surfaces such as the launcher label.
  static const String appNameShort = ${dartString(copy.appNameShort)};

  /// \`MaterialApp.title\` - what the OS task switcher shows.
  static const String appTitle = ${dartString(copy.appTitle)};

  /// One-line positioning statement.
  static const String tagline = ${dartString(brand.brand.tagline)};

  /// Splash headline and the line beneath it.
  static const String splashTitle = ${dartString(copy.splashTitle)};
  static const String splashSubtitle = ${dartString(copy.splashSubtitle)};

  /// Longer marketing copy on the sign-in sheet.
  static const String loginTagline = ${dartString(copy.loginTagline)};

  /// Legal entity behind the app.
  static const String legalEntity = ${dartString(brand.brand.legalEntity)};

  // --- Links -------------------------------------------------------------

  static const String website = ${dartString(urls.website)};
  static const String termsAndConditions = ${dartString(urls.termsAndConditions)};
  static const String privacyPolicy = ${dartString(urls.privacyPolicy)};
  static const String contactEmail = ${dartString(urls.contactEmail)};

  /// Null when the fork does not run a Discord.
  static const String? discordInvite = ${discord};

  static const String sourceRepo = ${dartString(urls.sourceRepo)};

  // --- Updates -----------------------------------------------------------

  /// Where the in-app updater looks for a newer version, and where "Update now"
  /// sends the user. All three are null when the fork has not published
  /// anywhere - the update check is then skipped and nothing is fetched.
  ///
  /// [updateFeedUrl] is a Sparkle-style appcast and wins over the store
  /// listings on both platforms.
  static const String? playStoreUrl = ${playStoreUrl};
  static const String? appStoreUrl = ${appStoreUrl};
  static const String? updateFeedUrl = ${updateFeedUrl};

  /// Reverse-DNS application identifier, shared by both platforms.
  static const String bundleId = ${dartString(identifiers.bundleId)};
}
`;
};

// ---------------------------------------------------------------------------
// apps/mobile/lib/src/core/theme/brand_palette.dart
// ---------------------------------------------------------------------------

export const BRAND_PALETTE_PATH =
  "apps/mobile/lib/src/core/theme/brand_palette.dart";

export const buildBrandPaletteDart = (brand: Brand): string => {
  const { theme } = brand;

  const groups = TOKEN_GROUPS.map((group) => {
    const body = group.tokens
      .map((token) => {
        const pair = theme.palette[token];
        if (pair === undefined) {
          return "";
        }
        const source = theme.overrides[token] !== undefined ? " (overridden)" : "";
        return [
          `  /// \`C.${token}\`${source}`,
          `  static const Color ${token}Light = ${dartColor(pair.light)};`,
          `  static const Color ${token}Dark = ${dartColor(pair.dark)};`,
        ].join("\n");
      })
      .filter((entry) => entry.length > 0)
      .join("\n\n");

    return `  // --- ${group.title} ${"-".repeat(Math.max(1, 66 - group.title.length))}\n\n${body}`;
  }).join("\n\n");

  const tintNote =
    theme.tint === 0
      ? "No tint: the neutral tokens are upstream's, unchanged."
      : `Tinted at ${theme.tint} - the neutrals carry up to ${Math.round(theme.tint * MAX_TINT * 100)}% of the accent.`;

  return `${GENERATED_HEADER}

import "package:flutter/material.dart";

/// Every colour token, resolved from packages/brand/brand.json.
///
/// \`colors.dart\` reads from here rather than carrying literals, which is what
/// makes the palette reachable from a config file at all. Values come from the
/// accent, then the tint, then \`theme.overrides\` - each stage able to overrule
/// the one before it.
///
/// ${tintNote}
class BrandPalette {
  const BrandPalette._();

${groups}

  // --- Aliases ${"-".repeat(56)}

  /// Kept so that a tree rebranded by an earlier version of the engine - where
  /// \`colors.dart\` referenced \`accentLight\` directly - still compiles.
  static const Color accentLight = brandAccentLight;
  static const Color accentDark = brandAccentDark;

  // --- Launch screen ${"-".repeat(50)}

  /// These must stay in sync with the iOS \`LaunchBackground\` /
  /// \`LaunchForeground\` colour sets, which the engine regenerates from the
  /// same values.
  static const Color launchBackgroundLight = ${dartColor(theme.launchBackgroundLight)};
  static const Color launchBackgroundDark = ${dartColor(theme.launchBackgroundDark)};
  static const Color launchForegroundLight = ${dartColor(theme.launchForegroundLight)};
  static const Color launchForegroundDark = ${dartColor(theme.launchForegroundDark)};
}
`;
};

// ---------------------------------------------------------------------------
// apps/mobile/lib/src/core/theme/colors.dart
// ---------------------------------------------------------------------------

export const COLORS_DART_PATH = "apps/mobile/lib/src/core/theme/colors.dart";

/** Splits `colors.dart` at the boundary between the two factories. */
const DARK_FACTORY_MARKER = "factory C.dark()";

export interface ColorsPatch {
  text: string;
  /** Tokens rewritten, per mode. */
  rewritten: number;
  /**
   * Literals that did not match the brand the engine believes is applied -
   * i.e. somebody hand-edited `colors.dart`. Reported, not fatal.
   */
  drifted: string[];
}

/**
 * Rewrites every colour literal in `colors.dart` into a reference to the
 * generated `BrandPalette`.
 *
 * The file declares each token twice, once per factory, so the two halves are
 * patched separately - the token name alone is ambiguous (`textInversePrimary`
 * and `neutralWhite` are both `0xFFFFFFFF` in light mode), but token name plus
 * which side of `factory C.dark()` it falls on is not.
 *
 * Only `<token>: const Color(0x...)` is matched, which is why the constructor's
 * `required this.textPrimary,` parameters and the shared gradient definitions
 * are left alone. Idempotent: a second run finds `BrandPalette.textPrimaryLight`
 * where the literal used to be and matches nothing.
 */
export const patchColorsDart = (
  source: string,
  previous: Brand
): ColorsPatch => {
  const boundary = source.indexOf(DARK_FACTORY_MARKER);
  if (boundary === -1) {
    return { text: source, rewritten: 0, drifted: [] };
  }

  const drifted: string[] = [];
  let rewritten = 0;

  const patchHalf = (half: string, mode: "light" | "dark"): string => {
    const suffix = mode === "light" ? "Light" : "Dark";
    let out = half;

    for (const token of TOKEN_NAMES) {
      const pattern = new RegExp(
        `(\\b${token}:\\s*)const Color\\((0x[0-9A-Fa-f]{8})\\)`
      );
      out = out.replace(pattern, (_match, prefix: string, literal: string) => {
        rewritten += 1;
        const expected = previous.theme.palette[token]?.[mode];
        if (expected !== undefined && literal.toUpperCase() !== expected.toUpperCase()) {
          drifted.push(`${token} (${mode}): found ${literal}, expected ${expected}`);
        }
        return `${prefix}BrandPalette.${token}${suffix}`;
      });
    }

    return out;
  };

  return {
    text:
      patchHalf(source.slice(0, boundary), "light") +
      patchHalf(source.slice(boundary), "dark"),
    rewritten,
    drifted,
  };
};

// ---------------------------------------------------------------------------
// apps/mobile/lib/src/core/theme/brand_shape.dart
// ---------------------------------------------------------------------------

export const BRAND_SHAPE_PATH =
  "apps/mobile/lib/src/core/theme/brand_shape.dart";

export const buildBrandShapeDart = (brand: Brand): string => {
  const { style, scale } = brand.theme.shape;

  return `${GENERATED_HEADER}

/// The corner-radius scale.
///
/// Style: \`${style}\`. Change it in packages/brand/brand.json under
/// \`theme.shape\`, or override an individual step under \`theme.shape.scale\`.
///
/// The widget tree references these instead of literal radii, so the app's
/// silhouette is part of the brand rather than something hard-coded in 180
/// places. Every radius in the app is on this scale - there are no off-scale
/// one-offs left, which is what makes a shape style reach the whole product
/// rather than just the widgets that happened to use round numbers.
///
/// Reach for these through \`context.radii\` rather than importing this file:
/// \`AppRadii\` wraps them as ready-made \`BorderRadius\` values.
class BrandShape {
  const BrandShape._();

  /// Grabbers, progress bars, hairline indicators.
  static const double radiusHairline = ${scale.hairline};

  /// Chips, badges, small inputs.
  static const double radiusXs = ${scale.xs};

  /// Small chips and inline pills.
  static const double radiusXsPlus = ${scale.xsPlus};

  /// Buttons, list rows, thumbnails.
  static const double radiusSm = ${scale.sm};

  /// Compact cards and banners.
  static const double radiusSmPlus = ${scale.smPlus};

  /// The workhorse: cards, sheets, most containers.
  static const double radiusMd = ${scale.md};

  /// Cards that sit above other cards.
  static const double radiusMdPlus = ${scale.mdPlus};

  /// Large cards and modals.
  static const double radiusLg = ${scale.lg};

  /// Bottom sheet tops and full-width panels.
  static const double radiusLgPlus = ${scale.lgPlus};

  /// Hero panels.
  static const double radiusXl = ${scale.xl};

  /// Stadium-ish buttons that are not quite pills.
  static const double radiusXlPlus = ${scale.xlPlus};

  /// Avatars and pill buttons. A sentinel meaning "clamp to half the shorter
  /// side" - it is not scaled by the style, because "sharp" should not turn a
  /// circular avatar into a rounded square.
  static const double radiusFull = ${scale.full};
}
`;
};

// ---------------------------------------------------------------------------
// apps/mobile/lib/src/core/theme/brand_space.dart
// ---------------------------------------------------------------------------

export const BRAND_SPACE_PATH =
  "apps/mobile/lib/src/core/theme/brand_space.dart";

const SPACE_STEP_DOC: Readonly<Record<string, string>> = {
  none: "No gap. Zero in every density - the absence of spacing, not a small amount of it.",
  xxs: "Hairline separation: an icon from its label.",
  xs: "Tight pairs inside a control.",
  xsPlus: "Chip and badge padding.",
  sm: "The small gap: between a title and its subtitle.",
  smPlus: "Compact list rows.",
  md: "Between related elements in a card.",
  mdPlus: "Card padding on dense screens.",
  lg: "The workhorse: screen margins and card padding.",
  lgPlus: "Between sections of a form.",
  xl: "Between major sections.",
  xlPlus: "Above a primary action.",
  xxl: "Screen-level breathing room.",
  huge: "Empty-state and hero spacing.",
};

export const buildBrandSpaceDart = (brand: Brand): string => {
  const { style, scale } = brand.theme.space;

  const steps = SPACE_STEPS.map(
    (step) => `  /// ${SPACE_STEP_DOC[step] as string}
  static const double ${step} = ${scale[step]};`
  ).join("\n\n");

  return `${GENERATED_HEADER}

/// The spacing scale.
///
/// Density: \`${style}\`. Change it in packages/brand/brand.json under
/// \`theme.space\`, or override an individual step under \`theme.space.scale\`.
///
/// Every gap and every pad in the app is on this scale. Density is the axis
/// that survives a palette swap: two apps sharing a colour, a corner radius and
/// a typeface still read as different products when one breathes and the other
/// is packed.
///
/// Reach for these through \`AppSpacing\`, which wraps them as ready-made
/// \`EdgeInsets\`, rather than importing this file.
class BrandSpace {
  const BrandSpace._();

${steps}
}
`;
};

// ---------------------------------------------------------------------------
// apps/mobile/lib/src/core/theme/brand_type.dart
// ---------------------------------------------------------------------------

export const BRAND_TYPE_PATH =
  "apps/mobile/lib/src/core/theme/brand_type.dart";

/** `xl3Plus` -> `Xl3Plus`, for the generated constant names. */
const stepSuffix = (step: string): string =>
  step.charAt(0).toUpperCase() + step.slice(1);

/**
 * Flutter's `height` is a multiple of the font size, but a design system states
 * line height in pixels and so does every reference's CSS. The division is
 * emitted rather than evaluated so the generated file still reads as the
 * designed pair - `20 / 14` says "20px on a 14px face" where `1.4285714` says
 * nothing and drifts on the next edit.
 */
const lineHeightExpr = (size: number, lineHeight: number): string =>
  `${lineHeight} / ${size}`;

export const buildBrandTypeDart = (brand: Brand): string => {
  const { style, scale, weights } = brand.theme.type;

  const steps = TYPE_STEPS.map((step) => {
    const { size, lineHeight } = scale[step];
    return `  /// ${size}px on ${lineHeight}px.
  static const double size${stepSuffix(step)} = ${size};
  static const double height${stepSuffix(step)} = ${lineHeightExpr(size, lineHeight)};`;
  }).join("\n\n");

  return `${GENERATED_HEADER}

import "package:flutter/painting.dart";

/// The typographic scale.
///
/// Style: \`${style}\`. Change it in packages/brand/brand.json under
/// \`theme.type\`, override an individual step under \`theme.type.scale\`, or
/// move the weights under \`theme.type.weights\`.
///
/// \`app_text_theme.dart\` is built entirely from these, so the ramp is part of
/// the brand rather than forty literal \`fontSize:\`s. Two apps in the same
/// typeface still read as different products when this table differs, which is
/// why changing \`fonts.body\` alone never made a fork look like its own thing.
///
/// Reach for these through \`AppType\` or \`context.textTheme\` rather than
/// importing this file.
class BrandType {
  const BrandType._();

${steps}

  /// Body copy.
  static const FontWeight weightRegular = FontWeight.w${weights.regular};

  /// Emphasised body, secondary labels.
  static const FontWeight weightMedium = FontWeight.w${weights.medium};

  /// Headings and interactive labels.
  static const FontWeight weightSemibold = FontWeight.w${weights.semibold};

  /// Page titles and the display sizes.
  static const FontWeight weightBold = FontWeight.w${weights.bold};
}
`;
};

// ---------------------------------------------------------------------------
// apps/mobile/lib/src/core/theme/brand_fonts.dart
// ---------------------------------------------------------------------------

export const BRAND_FONTS_PATH =
  "apps/mobile/lib/src/core/theme/brand_fonts.dart";

export const buildBrandFontsDart = (brand: Brand): string => {
  const { fonts } = brand;

  return `${GENERATED_HEADER}

/// The four typeface roles.
///
/// \`app_text_theme.dart\` names these instead of literal family strings, so a
/// fork changes its typography in packages/brand/brand.json rather than in
/// twenty \`TextStyle\`s. Every family named here is declared in
/// \`apps/mobile/pubspec.yaml\`; the engine refuses to write a family that is
/// not, because Flutter falls back to the system face for an unknown family
/// without reporting an error.
class BrandFonts {
  const BrandFonts._();

  /// Headlines and the splash wordmark.
  static const String display = ${dartString(fonts.display)};

  /// Body copy and UI labels - by far the most used.
  static const String body = ${dartString(fonts.body)};

  /// Numerals, timestamps, identifiers.
  static const String mono = ${dartString(fonts.mono)};

  /// The character face, used sparingly for large display numerals.
  static const String accent = ${dartString(fonts.accent)};
}
`;
};

// ---------------------------------------------------------------------------
// apps/mobile/lib/src/core/config/constants/attribution.dart
// ---------------------------------------------------------------------------

export const ATTRIBUTION_DART_PATH =
  "apps/mobile/lib/src/core/config/constants/attribution.dart";

export const buildAttributionDart = (brand: Brand): string => {
  const a = brand.attribution;
  return `${GENERATED_HEADER}
//
// This file intentionally retains UPSTREAM branding. It is excluded from the
// rename engine (see NEVER_REWRITE in packages/brand/lib/fileindex.ts) so that the
// credit survives a rebrand instead of being renamed along with everything
// else. packages/brand/verify.ts asserts both directions: that the old brand name
// appears nowhere outside files like this one, and that it still appears here.

/// Credit to the upstream project this app is forked from.
class Attribution {
  const Attribution._();

  /// Set \`attribution.enabled: false\` in packages/brand/brand.json to hide the credit.
  /// Note that the licence still requires you to retain LICENSE and the
  /// copyright notice regardless of this flag.
  static const bool enabled = ${a.enabled};

  static const String upstreamName = ${dartString(a.upstreamName)};
  static const String upstreamOrg = ${dartString(a.upstreamOrg)};
  static const String upstreamRepo = ${dartString(a.upstreamRepo)};

  /// Short credit line, shown in the profile footer.
  static const String text = ${dartString(a.text)};

  static const bool showInProfileFooter = ${a.showInProfileFooter};
}
`;
};

// ---------------------------------------------------------------------------
// Native copy
// ---------------------------------------------------------------------------

export const STRINGS_XML_PATH =
  "apps/mobile/android/app/src/main/res/values/strings.xml";

/**
 * Rewrites only the two brand strings, leaving `default_web_client_id` alone -
 * that value belongs to `apps/mobile/tool/sync_google_client_ids.dart`, which
 * derives it from `.env`. Two tools writing one file is how you get a merge
 * conflict in a generated artefact.
 */
export const patchStringsXml = (xml: string, brand: Brand): string =>
  xml
    .replace(
      /<string name="app_name">[^<]*<\/string>/,
      `<string name="app_name">${escapeXml(brand.copy.appName)}</string>`
    )
    .replace(
      /<string name="app_name_short">[^<]*<\/string>/,
      `<string name="app_name_short">${escapeXml(brand.copy.appNameShort)}</string>`
    );

const escapeXml = (value: string): string =>
  value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

export const INFO_PLIST_PATH = "apps/mobile/ios/Runner/Info.plist";

const PLIST_USAGE_KEYS: ReadonlyArray<[string, keyof Brand["copy"]["iosUsageDescriptions"]]> = [
  ["NSCameraUsageDescription", "camera"],
  ["NSMotionUsageDescription", "motion"],
  ["NSPhotoLibraryUsageDescription", "photoLibrary"],
  ["NSPhotoLibraryAddUsageDescription", "photoLibraryAdd"],
  ["NSMicrophoneUsageDescription", "microphone"],
  ["NSSpeechRecognitionUsageDescription", "speechRecognition"],
];

/**
 * Sets the display names and the six permission prompts.
 *
 * The permission strings are what the OS shows the user at the moment it asks
 * for the camera or their photo library, and they name the company. A token
 * rename would turn "FPV Labs uses your camera" into the fork's legal entity,
 * which reads oddly; taking them from `copy.iosUsageDescriptions` lets a fork
 * write its own, and defaults to a sentence built from the app name.
 */
export const patchInfoPlist = (plist: string, brand: Brand): string => {
  let out = plist
    .replace(
      /(<key>CFBundleDisplayName<\/key>\s*<string>)[^<]*(<\/string>)/,
      `$1${escapeXml(brand.copy.appName)}$2`
    )
    .replace(
      /(<key>CFBundleName<\/key>\s*<string>)[^<]*(<\/string>)/,
      `$1${escapeXml(brand.copy.appNameShort)}$2`
    );

  for (const [key, field] of PLIST_USAGE_KEYS) {
    const pattern = new RegExp(`(<key>${key}</key>\\s*<string>)[\\s\\S]*?(</string>)`);
    out = out.replace(
      pattern,
      `$1${escapeXml(brand.copy.iosUsageDescriptions[field])}$2`
    );
  }

  return out;
};

// ---------------------------------------------------------------------------
// iOS colour sets
// ---------------------------------------------------------------------------

const srgbComponent = (value: number): string => (value / 255).toFixed(3);

/**
 * An `.colorset` Contents.json with a light entry and a dark-appearance entry,
 * matching the structure Xcode writes.
 */
export const buildColorsetJson = (light: Hex, dark: Hex): string => {
  const entry = (hex: Hex, darkAppearance: boolean): Record<string, unknown> => {
    const { r, g, b, a } = hexToRgba(hex);
    return {
      ...(darkAppearance
        ? { appearances: [{ appearance: "luminosity", value: "dark" }] }
        : {}),
      color: {
        "color-space": "srgb",
        components: {
          alpha: (a / 255).toFixed(3),
          blue: srgbComponent(b),
          green: srgbComponent(g),
          red: srgbComponent(r),
        },
      },
      idiom: "universal",
    };
  };

  return `${JSON.stringify(
    {
      colors: [entry(light, false), entry(dark, true)],
      info: { version: 1, author: "xcode" },
    },
    null,
    2
  )}\n`;
};

export const LAUNCH_BACKGROUND_COLORSET =
  "apps/mobile/ios/Runner/Assets.xcassets/LaunchBackground.colorset/Contents.json";
export const LAUNCH_FOREGROUND_COLORSET =
  "apps/mobile/ios/Runner/Assets.xcassets/LaunchForeground.colorset/Contents.json";

// ---------------------------------------------------------------------------
// Launch screen storyboard
// ---------------------------------------------------------------------------

export const STORYBOARD_PATH =
  "apps/mobile/ios/Runner/Base.lproj/LaunchScreen.storyboard";

/**
 * Patches the storyboard surgically rather than regenerating it.
 *
 * `flutter_native_splash` would rewrite this file from its own template and
 * destroy the custom two-label, full-bleed-texture layout - so the engine
 * edits exactly four things: the two label strings, and the `<namedColor>` RGB
 * blocks. Those colour blocks are a cache Xcode keeps in sync with the
 * `.colorset` files; edit only the colorset and Interface Builder will show you
 * the old colour forever.
 */
export const patchStoryboard = (xml: string, brand: Brand): string => {
  let out = xml
    .replace(
      /(<label[^>]*id="Ste-la-bl1"[^>]*)/,
      (match) => match.replace(/text="[^"]*"/, `text="${escapeXml(brand.copy.splashTitle)}"`)
    )
    .replace(
      /(<label[^>]*id="Fpv-la-bl2"[^>]*)/,
      (match) =>
        match.replace(/text="[^"]*"/, `text="${escapeXml(brand.copy.splashSubtitle)}"`)
    );

  const namedColor = (name: string, hex: Hex): void => {
    const { r, g, b, a } = hexToRgba(hex);
    const pattern = new RegExp(
      `(<namedColor name="${name}">\\s*)<color[^/]*/>`,
      "m"
    );
    out = out.replace(
      pattern,
      `$1<color red="${srgbComponent(r)}" green="${srgbComponent(g)}" blue="${srgbComponent(b)}" alpha="${(a / 255).toFixed(3)}" colorSpace="custom" customColorSpace="sRGB"/>`
    );
  };

  namedColor("LaunchForeground", brand.theme.launchForegroundLight);
  namedColor("LaunchBackground", brand.theme.launchBackgroundLight);

  return out;
};
